### ISSUE TITLE
Prompt to ask whether images are to be downloaded or not at activity launch 

### ISSUE THREAD

**Issue by siddharth2610** [xoodle/frost#19]

**Comment by aryanshar** [comment]
Fixed !

**Comment by ubarsaiyan** [comment]
Not fixed @aryanshar 
No popup appears asking me to download images at activity launch.

**Comment by ubarsaiyan** [comment]
@aryanshar Don't keep closing an issue which is not fixed.

**Comment by varunkhare1234** [comment]
Its fixed now i think
